### ISSUE TITLE
Wrong query parameter name pagesize

### ISSUE THREAD

**Issue by aapris** [ForumViriumHelsinki/traffic-counters-map#1]
This should probably be `page_size` instead of `pagesize`.
https://github.com/ForumViriumHelsinki/traffic-counters-map/blob/8beab723fef7cdc47eb92bc62cfdc763285cdfbe/src/server.js#L170

See https://github.com/City-of-Helsinki/lidotiku/blob/5f38c72df6ceb66534cc3b13a8a83291d2edddf7/api/views.py#L34

**Comment by juhanikantola** [comment]
True, but it is also hard coded previously here: https://github.com/ForumViriumHelsinki/traffic-counters-map/blob/8beab723fef7cdc47eb92bc62cfdc763285cdfbe/src/server.js#L164
